### ISSUE TITLE
railway=subway does not get rendered when being on the ground (no layer= or layer >= 0 or no level= or level >= 0)

### ISSUE THREAD

**Issue by osm-ToniE** [StrandedKitty/streets-gl#10]
I don't now what the best combination of (missing) values for layer and/or level would be to have the subway rendered/not rendered

- https://www.openstreetmap.org/way/8108342 is on the ground
- https://www.openstreetmap.org/way/158659291#map=19/48.09093/11.64365 is underground

https://streets.gl/#48.09036,11.64369,50.00,1.50,209.69

**Comment by StrandedKitty** [comment]
Thank you, fixed in https://github.com/StrandedKitty/streets-gl/commit/f9769a7c938562b7e745ed1385eeefa1160300a3. I've also added support for [gauge=*](https://wiki.openstreetmap.org/wiki/Key:gauge) and some other railway types.
