### ISSUE TITLE
Glitch at conflicting colour/material of building and building:part 

### ISSUE THREAD

**Issue by Discostu36** [StrandedKitty/streets-gl#103]
**Describe the bug**
When there is a `building` footprint that is not wholly covered by `building:part`s, but the ladder is only used to describe a part of the building that is different from the rest, the colour/material of the `building` and of the `building:part` are rendered at the same time, leading to a glitch (flickering surface).

**Expected behavior**
The `building:part` should overwrite the properties of the `building`. In clear cases (unlike this one), it should inherit them (#98).

**Map location**
https://streets.gl/#54.32712,10.14138,29.25,50.75,109.19

**Screenshots**
![grafik](https://github.com/StrandedKitty/streets-gl/assets/30999326/537c619f-ba68-4914-8c0c-20d73e1b57a2)
https://www.openstreetmap.org/relation/3293733
https://www.openstreetmap.org/way/376148599

**System information**
 - OS: Windows 11
 - Browser with version: Firefox 113.0.1 (64-Bit)

**Additional context**
In this case, the building footprint is a multipolygon, I don't know if this is part of the problem.

**Comment by Discostu36** [comment]
Another example:
![grafik](https://github.com/StrandedKitty/streets-gl/assets/30999326/c79995e4-9911-457a-836e-a6be92638561)
https://streets.gl/#54.33057,10.12366,38.25,201.00,80.94
https://www.openstreetmap.org/way/90393644
https://www.openstreetmap.org/way/984489872

**Comment by StrandedKitty** [comment]
This is expected. I don't think it's possible to make a straightforward algorithm that would detect overlapping buildings, there's just too many edge cases.

To fix this particular problem you can add `building:min_level=1` to the way №376148599.
