### ISSUE TITLE
Potentially even better terrain for Europe

### ISSUE THREAD

**Issue by hb0nd** [StrandedKitty/streets-gl#104]
https://github.com/orgs/organicmaps/discussions/5170

**Comment by StrandedKitty** [comment]
Does this dataset contain terrain elevation or just global elevation (including buildings, trees, etc)? The latter won't work.

**Comment by Matthias84** [comment]
(DEM vs. DTM)

**Comment by sekerob** [comment]
Though the 3D terrain feature is very pleasing from a helicopter view overlooking the country side, the reality is that lots of buildings are still being eaten or swallowed whole. Today mapped details of a school area in Loreto Aprutino, main building details and sports_hall, colorimeter in operation. The terrain has been evened long ago, the buildings are previous millennium, but with terrain enabled it looks like this

![image](https://github.com/StrandedKitty/streets-gl/assets/23308504/d86c3af4-2135-494b-867c-7fe4644f55af)

terrain disabled shows the 'realler' picture

![image](https://github.com/StrandedKitty/streets-gl/assets/23308504/45446d88-1f48-41a2-87ae-3457374604ee)

The equal_hipped is truly realistic.

**Comment by hb0nd** [comment]
it's DSM sadly
