### ISSUE TITLE
roof:orientation with roof:shape=skillion tilts roof in both ways

### ISSUE THREAD

**Issue by guerda** [StrandedKitty/streets-gl#107]
**Describe the bug**
Similar to #55, the roof orientation does not show correctly with the `roof:shape=skillion`. It seems that the skillion is tilted in both ways at the same time.
You can see that if you view a building from two sides:

**Expected behavior**
The skillion should only be tilted in one direction. The ridge should be across to the longest side of the building in that case.

**Map location**
https://streets.gl/#51.24158,6.70798,42.67,132.27,416.09

**Screenshots**
![image](https://github.com/StrandedKitty/streets-gl/assets/230782/701d3503-c3e2-46a1-85b4-189bdcc858b0)
![image](https://github.com/StrandedKitty/streets-gl/assets/230782/125cd990-d2f2-4560-9756-06b4e21110f2)
![image](https://github.com/StrandedKitty/streets-gl/assets/230782/69e90235-a4d1-4c81-a846-d4f76675a18b)

Both screenshots show the same buildings, once from south south west and from north west.
They all have roof:shape=skillion and roof:orientation=across.

**System information**
 - OS: Windows 10
 - Browser with version: Chrome 113

**Comment by sekerob** [comment]
With these one sided roofs like skillion and sloped I restarted adding roof:direction=* in degrees. Sofar the rendering seems to show correctly for me this way. Otherwise it's a guess which way the rain flows.

**Comment by StrandedKitty** [comment]
Implemented in https://github.com/StrandedKitty/streets-gl/commit/266dd75c9766dd69459d5cd1d5719b5e552721ad, it should work fine now. 

Note that it's not the best choice to use `roof:orientation` on non-symmetrical roof shapes such as `skillion` or `saltbox`. With this kind of tagging it's always possible to render a roof in two different ways. So it's better to use `roof:direction` instead as it clearly specifies which way the roof is facing.

![image](https://github.com/StrandedKitty/streets-gl/assets/48140945/4f49d38c-d200-48c4-b1cb-80aed3421170)

**Comment by guerda** [comment]
Thank you for fixing this!
