### ISSUE TITLE
Conflicting area:highway=footway with sidewalk rendering

### ISSUE THREAD

**Issue by Discostu36** [StrandedKitty/streets-gl#108]
**Describe the bug**
`area:highway=footway` and `sidewalk` tags are both rendered at the same time. This can lead to cases of a sidewalk being rendered twice, in the correct and incorrect location.

**Expected behavior**
When there is an `area:highway=footway` area close to a street, the `sidwalk` rendering on that side of the street should be canceled. Another solution would be to also render other `area:highway` tags so that they can overwrite the sidewalk rendering of the way.

**Map location**
https://streets.gl/#54.32602,10.11757,28.26,9.47,26.02

**Screenshots**
![grafik](https://github.com/StrandedKitty/streets-gl/assets/30999326/b55e7488-2431-4207-9515-9d4689a37b0b)

**System information**
 - OS: Windows 11
 - Browser with version: Firefox 113.0.1

**Comment by ivanbranco** [comment]
This looks like a lack of detail in OSM-database-side to me, not a rendering problem. A highway=footway should be drawn inside the area:highway (_"in addition to [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=[footway](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway) way tagged through their middle"_)

Is there a editing standard in Germany about mapping/not-mapping sidewalks as separate highways?

**Comment by Discostu36** [comment]
In Germany, sidewalks are usually only drawn as separate way if they are physically seperated from the carriageway (e.g. by grass, parking bay or similar)

**Comment by StrandedKitty** [comment]
You should use `sidewalk:both=separate` to specify that a sidewalk is mapped using a separate way.
See https://wiki.openstreetmap.org/wiki/Key:sidewalk

**Comment by Discostu36** [comment]
I know, but it isn't here.

**Comment by ivanbranco** [comment]
> You should use sidewalk:both=separate

This tag is to be used when there's a separate highway=footway, not a separate area:highway=footway 

> In Germany, sidewalks are usually only drawn as separate way if they are physically seperated from the carriageway

A kerb isn't enough?

**Comment by Discostu36** [comment]
> A kerb isn't enough?

Most editors think it isn't, but there is no clear consensus. A renderer should work with both tagging practices.

**Comment by waldyrious** [comment]
> This tag is to be used when there's a separate highway=footway, not a separate area:highway=footway

IIUC an `area:highway=footway` should still have a linear `highway=footway` along its centerline (or the main path(s) within the area). From the [wiki](https://wiki.openstreetmap.org/wiki/Tag:area:highway%3Dfootway#Tagging_mistakes_to_avoid):

> Don't create an `area:highway=footway` area without also creating a linear `highway=footway` way along the centerline of the footway.
