### ISSUE TITLE
3D features ignore terrain elevation 

### ISSUE THREAD

**Issue by bloerwald** [StrandedKitty/streets-gl#110]
**Describe the bug**

With terrain elevation turned on, everything is floating in the air. Location is irrelevant, only determines how high things float.

**Expected behavior**

Things should clamp to the ground.

**Screenshots**

![image](https://github.com/StrandedKitty/streets-gl/assets/2866005/9610b7b2-0e6d-42d2-a8e9-4f089ea034e8)
![image](https://github.com/StrandedKitty/streets-gl/assets/2866005/97bd9129-938d-43d2-b8d0-fb6f5babddb5)

**System information**
 - OS: macOS Ventura 13.3.1 (22E261)
 - Browser with version: Safari 16.4 (18615.1.26.11.23)

**Additional context**

Console shows possibly related warning:

    [Log]     Vendor: Apple Inc.                         (main.460c71927472f098d2fd.js, line 4206)
              Renderer: Apple GPU
    [Warning] Couldn't sample height                     (main.460c71927472f098d2fd.js, line 4192, x6)

**Comment by ivanbranco** [comment]
Seems to be a Safari related problem, reported also with Safari 16.3 ([link](https://community.openstreetmap.org/t/streets-gl-a-new-3d-renderer-for-osm/98594/57))

**Comment by kayD** [comment]
I experience a possibly related problem #133

**Comment by wiesmann** [comment]
I'm seeing the same issue with Safari 16.5.2, note that the buildings on the nearby mountain (Züriberg) at around 600m altitude seem to correctly elevated, while the buildings in the plains (~430m) seem to be flying. 


![StreetsGl2](https://github.com/StrandedKitty/streets-gl/assets/398765/a9f5aaf5-7fe4-48cd-baf6-7881423beb21)
![StreetsGL1](https://github.com/StrandedKitty/streets-gl/assets/398765/fe140556-7b4c-42ef-8eb3-3a822b8f00f7)

**Comment by kayD** [comment]
@wiesmann 
It would be nice to know if on Safari the strange behavior shown in [133#issuecomment-1611086030](https://github.com/StrandedKitty/streets-gl/issues/133#issuecomment-1611086030) is also present.

**Comment by bloerwald** [comment]
> It would be nice to know if on Safari the strange behavior shown in [133#issuecomment-1611086030](https://github.com/StrandedKitty/streets-gl/issues/133#issuecomment-1611086030) is also present.

Not that exact behavior, but it really *is* weird: https://www.youtube.com/watch?v=o66AbxiUXxE

- pressed only a s and d, then panned with mouse a bit
- Safari 16.4 (18615.1.26.11.23).

**Comment by gy-mate** [comment]
The issue still persists in Safari `17.2.1`.

**Comment by StrandedKitty** [comment]
@bloerwald @ivanbranco @kayD @wiesmann @gy-mate
Hi guys, please let me know if any of you can still reproduce this problem. It seems like there is a bug in some webgl implementations related to immutable textures (or it's just me not using this part of the API properly), so I've changed the code a bit and it should be fixed now.

**Comment by gy-mate** [comment]
@StrandedKitty It works for me now, thanks a lot! :)

**Comment by kayD** [comment]
@StrandedKitty No issues with floating any more, neither on Firefox 120.0, nor on Vivaldi 6.5 (both on ubuntu)! Thanks so much!

**Comment by wiesmann** [comment]
Also fixed in Safari, thank you very much.

**Comment by bloerwald** [comment]
![image](https://github.com/StrandedKitty/streets-gl/assets/2866005/eb05108a-5f3b-4351-86ed-e9735ffcb393)
![image](https://github.com/StrandedKitty/streets-gl/assets/2866005/1f439404-86bc-4b80-a7ba-75f50aa604a6)

Original location to confirm, beautiful drop down to the neighbouring village. :)

**Comment by kayD** [comment]
@bloerwald which one is the correct image, the elevation in the second screenshot is much more pronounced (can be easily seen by flipping the two images back and forth). Was this another problem apart from the floating buildings?

**Comment by bloerwald** [comment]
> @bloerwald which one is the correct image, the elevation in the second screenshot is much more pronounced (can be easily seen by flipping the two images back and forth). Was this another problem apart from the floating buildings?

Bottom one is with enabled terrain, top with disabled, see settings in top right. Terrain was fine before, it was only the buildings from what I can remember. Features are now correctly attached to terrain.

**Comment by kayD** [comment]
Please excuse stupid me overlooking that setting... Thanks for the answer!
