### ISSUE TITLE
Roof:direction=across sometimes not considered?

### ISSUE THREAD

**Issue by Discostu36** [StrandedKitty/streets-gl#119]
**Describe the bug**
Tagging buildings with `roof:orientation=across` doesn't always to change roof direction, at least not for the gabled buildings I have just edited.

**Expected behavior**
`roof:orientation=across` should change the orientation of the roof.

**Map location**
https://streets.gl/#54.32350,10.11062,34.50,61.00,284.79

**Screenshots**
![grafik](https://github.com/StrandedKitty/streets-gl/assets/30999326/5738a7b7-c528-4740-8944-6690b275320a)

**System information**
 - OS: Windows 11
 - Browser with version: Firefox 113.0.1

**Additional context**
* I don't know if this is related to #107 
* I have purged and hard refreshed but it didn't change anything about the problem

**Comment by StrandedKitty** [comment]
You've confused [roof:direction](https://wiki.openstreetmap.org/wiki/Key:roof:direction) with [roof:orientation](https://wiki.openstreetmap.org/wiki/Key:roof:orientation).
