### ISSUE TITLE
Please recompress the PNGs

### ISSUE THREAD

**Issue by JensKorte** [StrandedKitty/streets-gl#126]
[ZopfliPNG](https://en.wikipedia.org/wiki/Zopfli#History) is a tool to recompress PNGs. I tried 3 images and saved between 7% and 40% of the size. I don't know if there are better tools available.

**Comment by StrandedKitty** [comment]
Currently, pngquant is used when building the application using Docker (https://github.com/StrandedKitty/streets-gl/blob/dev/Dockerfile#L23). It compresses all textures, reducing the resulting bundle size drastically. Note that it's lossy.
