### ISSUE TITLE
Buildings tagged as water_tower are rendered with windows

### ISSUE THREAD

**Issue by mippzon** [StrandedKitty/streets-gl#13]
Buildings tagged as water_tower are rendered with windows.

![image](https://user-images.githubusercontent.com/2655379/235926846-14322529-a5b2-4641-86ee-1f9a89bd8c2f.png)

**Comment by StrandedKitty** [comment]
Thank you. Fixed in https://github.com/StrandedKitty/streets-gl/commit/ba32d74fa423dec50f4eb50a33435b49e3d02fcb.
