### ISSUE TITLE
Outdated forest area is used for some areas

### ISSUE THREAD

**Issue by Zh9567** [StrandedKitty/streets-gl#130]
**Describe the bug**
I found out that in some areas the forest area is outdated as of at least a year ago. Some users had edited the area to avoid intersecting with major roads, major rivers, lakes, etc., or some new development at the area, or just some tagging mistakes. But on the map the trees still showing as of the outdated information.

**Expected behavior**
The forest area should be as of the latest version.

**Map location**
Some locations in my country:
https://streets.gl/#3.43367,101.80705,45.00,0.00,2364.45 (trees on a dam)
https://streets.gl/#4.55965,101.13711,45.00,0.00,1413.74 (trees on lakes and plantation)
https://streets.gl/#3.02755,101.25354,45.00,0.00,1991.06 (mangrove area mistagged as forest, and I have corrected it around a year ago)

**Comment by StrandedKitty** [comment]
Forest areas are rendered using Mapbox vector tiles as a source, so there's nothing I can do right now to fix this. They probably just don't update their data too often.

I'm currently working on building a custom vector tileset using [Planetiler](https://github.com/onthegomap/planetiler). This tileset is going to replace the data pulled from Overpass API and Mapbox.

**Comment by StrandedKitty** [comment]
This is no longer a problem, Mapbox data is no longer used.
