### ISSUE TITLE
don't render tunnel=culvert

### ISSUE THREAD

**Issue by Bauer33333** [StrandedKitty/streets-gl#131]
It seems like you are already not rendering streams with tunnel=yes, but if the type of tunnel is specified it shows up again, making the map look rather unpolished:
![grafik](https://github.com/StrandedKitty/streets-gl/assets/103360469/07ce00b7-b8a5-45c4-97f6-20abcccb673d)
Would be nice if all types of tunnel, unless they are tunnel=no, would not be rendered anymore.

**Comment by StrandedKitty** [comment]
Thank you. Fixed in https://github.com/StrandedKitty/streets-gl/commit/c0cd3c4c34414273c807731edbb1a8ae5220dde8.
