### ISSUE TITLE
MathUtils.shiftLeft / shiftRight can replace with >> << operator

### ISSUE THREAD

**Issue by deepkolos** [StrandedKitty/streets-gl#140]
https://github.com/StrandedKitty/streets-gl/blob/dev/src/lib/math/MathUtils.ts#L155

<img width="374" alt="image" src="https://github.com/StrandedKitty/streets-gl/assets/12824616/5b0e4b90-79b6-4d17-8631-481ef6047425">

**Comment by StrandedKitty** [comment]
It's not the same. Operators `<<` and `>>` always output 32 bit integers, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Left_shift

<img width="516" alt="Screenshot 2023-06-24 at 13 48 33" src="https://github.com/StrandedKitty/streets-gl/assets/48140945/651af60c-cf8e-4542-a041-a0b4ceb26c03">
