### ISSUE TITLE
Rendering broke out of the blue

### ISSUE THREAD

**Issue by ivanbranco** [StrandedKitty/streets-gl#141]
**Describe the bug**
This was the rendering before today: ![image](https://user-images.githubusercontent.com/94002623/236505473-3943ad8b-7703-4c5b-bc7e-a45cc9b33f1a.png)
This is the rendering today: 
![image](https://github.com/StrandedKitty/streets-gl/assets/94002623/5f366343-921b-4549-9924-4e4125fe8000)

Could this be related to the [recent changes](https://community.openstreetmap.org/t/streets-gl-a-new-3d-renderer-for-osm/98594/129)?

**Location**
[link](https://streets.gl/#45.33214,8.41699,19.75,212.75,30.65)

**System information**
 - OS: Windows 11 Home
 - Browser with version: Google Chrome V114.0.5735.134

**Comment by ivanbranco** [comment]
rendering got back to normal

**Comment by StrandedKitty** [comment]
I've only fixed it partially, unfortunately some kind of distortion/simplification is still there. This is not related to the frontend, this a problem with tiles generated using Planetiler. Not sure what is the exact cause.

<img width="935" alt="Screenshot 2023-08-06 at 00 50 38" src="https://github.com/StrandedKitty/streets-gl/assets/48140945/6ee9ec9c-55b6-4be1-96a2-9bf06a9fcc1b">

**Comment by StrandedKitty** [comment]
Made some improvements today, this building looks much better now. It seems like it's still not perfect, but good enough.

<img width="809" alt="Screenshot 2023-08-21 at 01 18 16" src="https://github.com/StrandedKitty/streets-gl/assets/48140945/3b707eac-2a46-4a08-a0ee-c28ffb52ad54">
