### ISSUE TITLE
The map isn't updating anymore with OSM endpoints

### ISSUE THREAD

**Issue by DabMK** [StrandedKitty/streets-gl#146]
**Describe the bug**
Recently added tags and features in OSM (roofs, building height) are not rendering even if you disable cached data. The weird thing is that some new building are rendering, but with no tags (but only a very small part). I waited more than 3 weeks, but they're still glitched

**Expected behavior**
The features and tags shouldn't be randomly ignored

**Map location**
https://streets.gl/#43.32876,11.32265,45.75,359.00,294.93

**Screenshots**
![Tags](https://github.com/StrandedKitty/streets-gl/assets/64862398/e2c81a50-f106-4e1d-bc22-aa8f8fc4ebaf)
![Building](https://github.com/StrandedKitty/streets-gl/assets/64862398/038c6a46-002c-4b09-8187-5613a533417e)
![Tags2](https://github.com/StrandedKitty/streets-gl/assets/64862398/bcaa4d6e-f7e1-4d0e-889d-0f4f9e0ca73b)
![Building2](https://github.com/StrandedKitty/streets-gl/assets/64862398/230e39ac-4825-4b2a-ace8-5fd158a73719)

**System information**
 - OS: Windows 10
 - Browser with version: Opera GX LVL5 (core: 99.0.4788.86)

**Additional context**
As you can see in the screenshots, some tags are being ignored in recent OSM changesets (some tags are also being ignored even in very old changesets)

**Comment by hb0nd** [comment]
another example: https://streets.gl/#51.47792,0.01343,27.24,35.00,355.88

looks like a similar issue to the one solved by https://github.com/StrandedKitty/streets-gl/pull/73?

**Comment by DabMK** [comment]
> another example: https://streets.gl/#51.47792,0.01343,27.24,35.00,355.88
> 
> looks like a similar issue to the one solved by #73?

In my issue even the roof material isn't rendering and this issue is more random

**Comment by StrandedKitty** [comment]
> another example: https://streets.gl/#51.47792,0.01343,27.24,35.00,355.88
> 
> looks like a similar issue to the one solved by #73?

roof:levels=0 here looks suspicious.

**Comment by Bauer33333** [comment]
For me it doesn't update at all anymore, eg. I have added levels to this building about two weeks ago, but they aren't visible yet despite showing the correct metadata: https://streets.gl/#48.78050,9.17288,45.00,0.00,261.83
![grafik](https://github.com/StrandedKitty/streets-gl/assets/103360469/300a91e0-eddd-45a5-b361-aae2369694d3)
Disabling "use cached tiles" doesn't do anything either, so it seems not to be an issue with that

**Comment by petrarca-arezzo** [comment]
Confirmed - same here (map isn't updated anymore whatever I try).

**Comment by mnalis** [comment]
related:
- https://github.com/StrandedKitty/streets-gl/issues/143
- https://community.openstreetmap.org/t/streets-gl-a-new-3d-renderer-for-osm/98594/146
