### ISSUE TITLE
Feature request: Print the date of the last tile update in the information screen.

### ISSUE THREAD

**Issue by sekerob** [StrandedKitty/streets-gl#151]
As per the feateure request title. On top of giving the 'users' a bearing on when the next run of tile updates will be it will doubtlessly also reduce the senseless Crtl+F5 to refresh the fetched data.

(if already somewhere, apologies for missing to discover this info snip).

**Comment by StrandedKitty** [comment]
Introduced in today's update, thank you for the suggestion.
<img width="274" alt="Screenshot 2023-08-06 at 21 02 56" src="https://github.com/StrandedKitty/streets-gl/assets/48140945/1756e80e-a9d9-4425-ac42-ba31b62a1961">
