### ISSUE TITLE
barrier=fence with height - rendered on wrong position

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [StrandedKitty/streets-gl#16]
I'm using height/min_height to define a fence at some ground level. 
See attached screenshots which show that the position in streets.gl is wrong.

streets.gl:

![Bild1](https://user-images.githubusercontent.com/57685590/235934217-4b87828a-c97c-4e59-a5ea-d78b12f4d4cc.jpg)

F4:

![Bild2](https://user-images.githubusercontent.com/57685590/235934250-37426cbb-ab46-4551-9872-b7a1139691a1.jpg)

**Comment by endim8** [comment]
link to building: https://www.openstreetmap.org/way/24874757

**Comment by StrandedKitty** [comment]
Thanks, I forgot about mercator scale factor for walls and fences. Fixed in https://github.com/StrandedKitty/streets-gl/commit/86816e4315181721554db858c33962caad0cb722.
