### ISSUE TITLE
How can I use it in an offline env?

### ISSUE THREAD

**Issue by ch0s1n** [StrandedKitty/streets-gl#175]
hello, I want to know how to replace the datasource by my own data, i have a private openstreetmap server in a offline environment, and I want to know how to use it.

**Comment by StrandedKitty** [comment]
You would have to generate some vector tiles using https://github.com/StrandedKitty/planetiler and serve them locally, and update the vector tiles URL in the config: https://github.com/StrandedKitty/streets-gl/blob/dev/src/app/Config.ts#L146

**Comment by Strubbl** [comment]
@ch0s1n Did you manage to run streets-gl with your own local data?

edit 2024-03-19: finally i did :)

**Comment by beautifulskymoon** [comment]
> You would have to generate some vector tiles using https://github.com/StrandedKitty/planetiler and serve them locally, and update the vector tiles URL in the config: https://github.com/StrandedKitty/streets-gl/blob/dev/src/app/Config.ts#L146

java -cp planetiler-dist/target/*-with-deps.jar com.onthegomap.planetiler.examples.StreetsProfile  failed  without StreetsProfile ，please help me

**Comment by alexandargyurov** [comment]
@beautifulskymoon try use the branch `shadowmap` and run the command again
