### ISSUE TITLE
roof goes through building

### ISSUE THREAD

**Issue by ivanbranco** [StrandedKitty/streets-gl#18]
I have a problem with [this](https://www.openstreetmap.org/relation/14861440/history) relation ([Streets GL URL](https://streets.gl/#45.35916,8.38974,17.50,61.75,67.60)), I don't understand if I did something wrong or if is a problem with the renderer.

The last floor (the second: [way252607457](https://www.openstreetmap.org/way/252607457/history)) is min_height=3 + **height=5.7**
the roof is **min_height=5.7** + height=8.7 ([w247047014](https://www.openstreetmap.org/way/247047014/history))

shouldn't this be fine?

![image](https://user-images.githubusercontent.com/94002623/235960751-c6df0252-876c-4b18-8eac-025c2d82a8cd.png)

**Comment by StrandedKitty** [comment]
Thank you for reporting this. The problem was that this roof doesn't have a height tag, and default roof height didn't take into account building height and min_height.

Fixed in https://github.com/StrandedKitty/streets-gl/commit/400e0fc4d94569fb7e5e338baeaf1eb095667cac.

**Comment by ivanbranco** [comment]
Thank you for fixing it!

> The problem was that this roof doesn't have a height tag, 

I don't understand tho, the roof building:part does have height=8.7, why you say it doesn't?

**Comment by StrandedKitty** [comment]
Sorry, I was referring to roof:height. The roof (https://www.openstreetmap.org/way/247047014/history) doesn't have this tag so the renderer needs to guess.

**Comment by ivanbranco** [comment]
Uhm, I understand its use when there building/building:part has a facade and a roof. But with building:part=roof there's no facade, that's why I used height only. Thanks for the explanation

**Comment by StrandedKitty** [comment]
Hmm, I guess you are right. I didn't think of it this way. So many edge cases...
