### ISSUE TITLE
Website Fails to Load Due to net::ERR_HTTP2_PROTOCOL_ERROR on index.js Resource

### ISSUE THREAD

**Issue by konmaz** [StrandedKitty/streets-gl#185]
### Bug Report

**Describe the bug**
The website fails to load due to an error in loading a resource. Specifically, the resource at `https://streets.gl/js/index.js` fails to load with the error: `net::ERR_HTTP2_PROTOCOL_ERROR`.

**Steps to Reproduce**
1. Open a web browser.
2. Navigate to the website [https://streets.gl](https://streets.gl).
3. Observe that the website does not load properly.
4. Open the browser's developer console (usually accessible via F12 or right-click -> "Inspect").
5. Check the console log for errors.

**Expected Behavior**
The website should load fully without any errors, and all resources, including `index.js`, should be loaded successfully.

**Map Location**
Not applicable.

**Screenshots**
![image](https://github.com/StrandedKitty/streets-gl/assets/58148103/1a1abb59-7afa-46b3-a8e0-c75f16f6c4b6)
![image](https://github.com/StrandedKitty/streets-gl/assets/58148103/49ff6985-f0e9-42eb-b2ca-2ac234058ada)
![image](https://github.com/StrandedKitty/streets-gl/assets/58148103/9cbb74a6-ecf8-4974-aab0-eced134b5363)

**System Information**
- **OS:** Windows 11 23H2
- **Browser with version:** Chrome 125.0.6422.142 (Official Build) (64-bit), Firefox 126.0.1 (64-bit)

**Additional Context**
Not applicable.

**Comment by cobalt32** [comment]
Also having this issue. Not loading on Chromium or Firefox-based browsers on Windows 11, Linux, or Android.

**Comment by StrandedKitty** [comment]
The server run out of space because it wasn't cleaning up logs. It should be online now.
