### ISSUE TITLE
The SSL certificate of the sample website has expired

### ISSUE THREAD

**Issue by yangyanggu** [StrandedKitty/streets-gl#186]
**Describe the bug**
The SSL certificate of the sample website has expired，https://streets.gl/

**Expected behavior**

**Map location**
If applicable, provide a link to the location on the map where the bug is observed.

**Screenshots**

**System information**
 - OS: [e.g. Windows 10]
 - Browser with version: [e.g. Chrome 113, Firefox 110]

**Additional context**

**Comment by StrandedKitty** [comment]
Thanks, done
