### ISSUE TITLE
Flat roofs on houses in the UK

### ISSUE THREAD

**Issue by egelmex** [StrandedKitty/streets-gl#19]
Flat rooves are rare in the UK on houses, A better default would probably be to assume gabled.
![image](https://user-images.githubusercontent.com/474014/235960816-a722d8a4-b2a1-4a63-b4c5-9080e2710d81.png)

Additionally flat rooves in the UK on houses are unlikely to be covered with plant equipment like the textures used. asphalt rooves are much more common.
 https://www.google.com/search?q=flat+roof+uk&rlz=1C1ONGR_en-GBGB987GB987&sxsrf=APwXEddAL1jFB0yAdU5hvCtoHyv_qSoMKg:1683127166109&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj72OOmudn-AhXEUMAKHSUJA8AQ_AUoAXoECAEQAw&biw=1537&bih=797&dpr=1

**Comment by c-h-r-i-s-t-i-a-n** [comment]
I'm  fine with the flat default, as it's the most neutral one. F4 is doing the same.

**Comment by StrandedKitty** [comment]
I don't think there should be regional default roof shapes. This would be really confusing.

**Comment by joshinils** [comment]
the only thing which is weird is the texture i feel, if it were to be an actual flat roof i'd be fine with tar paper and the other hinted stuff. but if no info is known then just put a neutral gray or red for tiles.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
I agree, maybe should be used on building=industrial only or so.

**Comment by ivanbranco** [comment]
To me the neutral flat is ok because it makes me understand that that place is missing a roof:shape value, if the value was more "common" (like gabled or hipped) I could assume it does have already the value and I would not improve the map

**Comment by Janjko** [comment]
> the only thing which is weird is the texture i feel, if it were to be an actual flat roof i'd be fine with tar paper and the other hinted stuff. but if no info is known then just put a neutral gray or red for tiles.

I like the textured flat roof, they look like ones I see around me.
