### ISSUE TITLE
`streets.gl` security certificate expired

### ISSUE THREAD

**Issue by Chiroyce1** [StrandedKitty/streets-gl#192]
Yes its unrelated to the project but I thought I'd mention this in an issue...

<img width="682" alt="image" src="https://github.com/user-attachments/assets/8a6c514f-b28c-4005-9143-0795ffe4d062" />
<img width="629" alt="image" src="https://github.com/user-attachments/assets/d403c8e2-cb1c-443c-9130-05602f106216" />

**Comment by StrandedKitty** [comment]
Thanks!
