### ISSUE TITLE
A wall memorial is rendered as a massive obelisk

### ISSUE THREAD

**Issue by ivanbranco** [StrandedKitty/streets-gl#2]
A memorial attached to a building outline is rendered as a massive obelisk that starts from the ground: [example](https://www.openstreetmap.org/node/2392567867/history)

![image](https://user-images.githubusercontent.com/94002623/235765870-c2cd2215-b6ae-4d57-be26-25240175983c.png)

I would expect such a big object to be rendered for a historic=monument, not historic=memorial.

**Comment by StrandedKitty** [comment]
Hi, thank you for reporting this. For now I've made so that this mesh is only rendered for `memorial=war_memorial`, `memorial=stele`, `memorial=obelisk`, `memorial=memorial`.

**Comment by Discostu36** [comment]
It seems that it is also rendered for missing `memorial=` tag. 
![grafik](https://github.com/StrandedKitty/streets-gl/assets/30999326/3dc98fd3-f4e6-471e-a8e6-a66efe3639f6)
https://www.openstreetmap.org/node/2674456165
Could you change that?
