### ISSUE TITLE
Feature Request: Refresh Map Data

### ISSUE THREAD

**Issue by egelmex** [StrandedKitty/streets-gl#20]
As a user making changes to the map I would like to be able to easily refresh the data for an area without having to reload all the textures speeding up the ability to review changes to the underlying map.

**Comment by StrandedKitty** [comment]
Thank yor for the suggestion. Implemented in https://github.com/StrandedKitty/streets-gl/commit/24767c6f0c9b4a0cd67faf37f954c33b49332aa0.
You can purge tiles by pressing Ctrl+P.
