### ISSUE TITLE
ubuntu can use different (or changeable) key definitions

### ISSUE THREAD

**Issue by rkiddy** [StrandedKitty/streets-gl#23]
For example, on my hardware, I do not know how to get a "middle mouse click". I could probably figure out, but if the UI is more configurable, I would be able to set the keys to something more obvious for my platform.

By the way, I am excited to see this project. I hope it lives on.

As I can, I will figure out ways to help.

By the by, I am using firefox 112.0.2 on Ubuntu 22.04.2 LTS.

**Comment by StrandedKitty** [comment]
Hmm, do you use a mouse that doesn't have a middle button? I didn't know such exist...
To be fair, this action that's mapped to MMB is not that usefull. It does camera zoom like in DayZ, so basically temporarily reduces your FOV by the factor of 2.

**Comment by rkiddy** [comment]
This might be just pilot error here. I am using a trackpad only. It turns out that a two-finger spread works to zoom the view. A double-click in the view did nothing, and that seemed odd. But, there is a way to zoom that is easy.

Not so much for web stuff, but apps often have issues with the UI on ubuntu and so I am prehaps over-sensitive to that. I will double-check and report anything else (anything real, I hope) that I find. Until then, I will close this.

much thanx
