### ISSUE TITLE
lane_markings always shown

### ISSUE THREAD

**Issue by joshinils** [StrandedKitty/streets-gl#24]
all driveways and all streets seem to have lane_markings, is that the correct default?
at least if a width is known, which is too small for two lanes, then don't draw them.
or never for driveways and other highway=service?

looks like this also depends on the surface, though almost all residential roads in germany don't have lane markings, even with surface=asphalt

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/118301063 https://streets.gl/#50.07755,19.92081,45.00,0.00,157.78

In this case it is reasonable to guess that there is a single lane here, not two lanes for cars (`oneway=yes`) - currently road renders too wide and eats sidewalk

But I am already amazed by rendering bicycle lane!

![screen01](https://user-images.githubusercontent.com/899988/236286007-b5d3e33c-3538-4315-a73d-27d6175356ac.png)

**Comment by StrandedKitty** [comment]
I've disabled markings for ways with `placement=transition` and `lane_markings=no`. Also now roads of types `service` and `living_street` have markings disabled by default (can be overridden by `lane_markings=yes`).

Default number of lanes for one-way roads is now cut in half. So one-way roads without `lanes` tag now have only one lane.
