### ISSUE TITLE
Roofs and building:min_level

### ISSUE THREAD

**Issue by ivanbranco** [StrandedKitty/streets-gl#25]
Hi vHawk,

me again with roofs, sorry. In #18 I had the building heights, but sometimes we work only with building:levels. In this case I have a building with two floors: [way/230178929](https://www.openstreetmap.org/way/230178929/history)

I had to create weird building:part shapes to render the main facade, that has two different colours for every floor (can be seen in the linked Commons [image](https://commons.wikimedia.org/wiki/File:Prestinari_166.jpg)), different from the colour of the three other facades. So I created a building:part for the roof with building:min_level=2 ([here](https://www.openstreetmap.org/way/1168367955/history))

The roof seems to have been added with building:min_level=1 tho (the triangle in the second floor): 
![image](https://user-images.githubusercontent.com/94002623/236058858-3a15cee3-3bee-43bb-9828-eda062a23a73.png)

**Comment by Beakerboy** [comment]
way 230178929 says the height is 6. This height is supposed to include the height from the ground to the top of the roof and should probably be 9 (https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings). The second floor building part says it is two floors tall and 6 meters. This means there's no available height left for the roof.
