### ISSUE TITLE
minor waterways

### ISSUE THREAD

**Issue by Matthias84** [StrandedKitty/streets-gl#33]
Sometimes there are small drains etc. that give structure to a area like [here in Rostock](https://streets.gl/#54.06865,12.11573,35.25,28.00,797.17). Would be nice to see them also in 3D and maybe with local adapted DEM?

Also how about fountains that might be a water source?

**Comment by StrandedKitty** [comment]
I've added waterways in https://github.com/StrandedKitty/streets-gl/commit/421645837bb8dcde41490f02da7c2780e904b9ad.
Supported waterway types are `river`, `stream`, `canal`, `drain`, `ditch`.

**Comment by sekerob** [comment]
The evidence...

![image](https://user-images.githubusercontent.com/23308504/236607400-fca06d7f-af1e-44c2-be85-390c964d62a4.png)

Yippee
