### ISSUE TITLE
Roof shading issues

### ISSUE THREAD

**Issue by waldyrious** [StrandedKitty/streets-gl#36]
I'm not sure what exactly might be causing this, but the roof sharing in these buildings is inconsistent for some reason:

![0x49zaf4ic](https://user-images.githubusercontent.com/478237/236157337-4557df4a-8538-4c1b-b0a7-76e9445e6a38.gif)

Link to the location: https://streets.gl/#16.67498,-22.93461,35.50,332.50,420.15

**Comment by ivanbranco** [comment]
> I'm not sure what exactly might be causing this, but the roof sharing in these buildings is inconsistent for some reason:

Some of these building have roof:orientation=*, same don't. Could be that?

**Comment by waldyrious** [comment]
Nice, thanks for the quick fix! Just for reference, linking another thread discussing roof lighting issues: #50.
