### ISSUE TITLE
Building not rendered

### ISSUE THREAD

**Issue by VladimirMorozov** [StrandedKitty/streets-gl#4]
https://www.openstreetmap.org/relation/14174935
https://streets.gl/#59.43650,24.73967,50.74,349.25,557.47

**Comment by ivanbranco** [comment]
This is because this building have a small building:part inside, so all the rest is ignored: https://www.openstreetmap.org/way/200921863/history

I guess this is a literally application of this part of the "Simple 3D Buildings" wiki: 

> The entire building outline should be filled with [building:part](https://wiki.openstreetmap.org/wiki/Key:building:part)=* areas

**Comment by VladimirMorozov** [comment]
Duplicate of https://github.com/StrandedKitty/streets-gl/issues/3 then
