### ISSUE TITLE
junction=roundabout implies oneway=yes

### ISSUE THREAD

**Issue by ivanbranco** [StrandedKitty/streets-gl#42]
When the lanes are more than 2 and oneway!=yes, Streets GL divides the lanes in forward and backward lanes, with a continue line 

![image](https://user-images.githubusercontent.com/94002623/236179849-902ded56-bf7d-4f9b-aa2d-4c5c1e9591ab.png)

in roundabouts there should not be a continue line, because junction=roundabout implies oneway=yes

**Comment by StrandedKitty** [comment]
Thank you. Fixed in https://github.com/StrandedKitty/streets-gl/commit/708e2d29d77b05745805e5ffe2195ded49a8f892.
