### ISSUE TITLE
Discord link is not valid

### ISSUE THREAD

**Issue by ivanbranco** [StrandedKitty/streets-gl#44]
If I press "i" and then "Discord Server" I get an "invitation not valid" warning:
![image](https://user-images.githubusercontent.com/94002623/236207671-b162bf06-38af-4fc7-b71d-5fa1627f2544.png)

DeepL:

> Invalid invitation
> This invitation may have expired or you do not have permission to log in.
> Continue on Discord
> Why is my invitation invalid?

**Comment by StrandedKitty** [comment]
Some other people also reported this, but I have no idea what's wrong.
