### ISSUE TITLE
Integration of better data source for elevation bitmap

### ISSUE THREAD

**Issue by lefuturiste** [StrandedKitty/streets-gl#46]
Here some thought :
Sometimes a terrain is poorly described in detail by the height bitmap because the variation are too brutal (for example an embankment, a retaining wall).
This is sadly out of OSM, but a realistic and accurate geographical description of reality should have a bitmap that is accurate enough especially if in proximity of buildings.
In France we have the [LIDAR HD](https://geoservices.ign.fr/lidarhd) initiative which could provide more detailed bitmap.
This is pretty big and there is no obvious way to do it, let alone the data for it.

**Comment by dreua** [comment]
Frankfurt Flughafen, on the other hand, looks quite bumpy: https://streets.gl/#50.04088,8.57643,11.75,228.00,3998.31

**Comment by StrandedKitty** [comment]
LIDAR data is great, but not for this application. Elevation data needs to be processed so that it represents only terrain without buildings.

**Comment by StrandedKitty** [comment]
It seems like arcgis has a free elevation layer: https://www.arcgis.com/home/item.html?id=58a541efc59545e6b7137f961d7de883
It's hard to tell if the quality is better than whatever Mapbox provides. Also this layer would have to be sliced into tiles and encoded into RGB format, so integrating it into Streets GL may take a while.

**Comment by StrandedKitty** [comment]
I've changed the elevation tileset from [Mapbox Terrain-RGB v1](https://docs.mapbox.com/data/tilesets/reference/mapbox-terrain-rgb-v1/) to Esri (ArcGIS) [Terrain 3D](https://elevation3d.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer). The quality is much better, so I think this is going to resolve most issues with bad elevation data.
