### ISSUE TITLE
some small building parts not rendered

### ISSUE THREAD

**Issue by endim8** [StrandedKitty/streets-gl#48]
maybe this is due to way simplification? ideally, simplification wouldn't completely remove a building:part

F4Map / StreetsGL
![bitmap](https://user-images.githubusercontent.com/26939824/236264060-97d6f04c-924e-4741-b96b-6fcc45f69919.png)
(slight roof difference due to F4Map being out of date)

https://www.openstreetmap.org/way/297997038

**Comment by StrandedKitty** [comment]
Fixed in https://github.com/StrandedKitty/streets-gl/commit/ff50ab974c07d5cb0d1c3d1c101fd8dc4b7b92ad.

**Comment by ivanbranco** [comment]
Uhm, something seems wrong here: 
![image](https://user-images.githubusercontent.com/94002623/236318394-6b3b5bdd-85bb-4792-a425-8a71d9e14cb1.png)

The black parts are not connected with the platform

**Comment by endim8** [comment]
i think this is because each building part gets its own offset from the sloped terrain, as opposed to getting one offset from the main building area and using it for all the contained building parts. But it's best to make a new issue for this :)
