### ISSUE TITLE
public_transport=stop_position is rendered as a bus shelter

### ISSUE THREAD

**Issue by ivanbranco** [StrandedKitty/streets-gl#5]
Hi, 

public_transport=stop_position is mapped as a bus shelter in the middle of the road. I would expect the bus shelter to be rendered for public_transport=platform only ([example](https://www.openstreetmap.org/node/2934256916/history))

![image](https://user-images.githubusercontent.com/94002623/235855149-8b45ea01-b58c-4bdb-a81d-2569996d68f8.png)

**Comment by osm-ToniE** [comment]
I think it's the **highway=bus_stop**, which gets rendered that way

https://streets.gl/#48.07814,11.65194,65.25,23.25,142.75

https://www.openstreetmap.org/#map=19/48.07793/11.65209

is OK, **highway=bus_stop** is not on but beside the street

**Comment by ivanbranco** [comment]
> is OK, highway=bus_stop is not on but beside the street

Fair enough, so this renderer served me as QA tool as well :p  
fixed

**Comment by osm-ToniE** [comment]
Shouldn't we re-open this or create a new issue with:

highway=bus_stop is rendered as a bus shelter even when being a node on the road

There is no common sense where to map a node highway=bus_stop. Some prefer it as a node on the street, some others as a node beside the street: both are seen as valid.

I also think that it should not be rendered as a bus stop shelter but rather as a pole or simple bus stop sign which does not bother even when rendered on the street? What and where shall a pole/icon be rendered if there is only a node highway=bus_stop on the street and nothing else?
