### ISSUE TITLE
Some roof normals seem incorrect

### ISSUE THREAD

**Issue by endim8** [StrandedKitty/streets-gl#50]
these sides of the roof should be in shadow, maybe the normals are being smoothed?

https://streets.gl/#51.47754,-0.06461,27.50,280.00,1015.51
![Screenshot from 2023-05-04 18-42-57](https://user-images.githubusercontent.com/26939824/236286127-d32cc78b-9e71-4a3a-8d81-ce4d3260117a.png)

**Comment by endim8** [comment]
the tiles normal map looks like it could be in worldspace or something, i'll try another and see if it fixes it

**Comment by endim8** [comment]
another case:
![image](https://user-images.githubusercontent.com/26939824/236293816-1576d9c5-c46d-4f27-afcd-b1be7e0574aa.png)
https://streets.gl/#51.47754,0.01439,14.50,295.75,175.26

**Comment by StrandedKitty** [comment]
Hmm, it's hard to say whether it's expected behaviour or not. Maybe the normal map is a bit too extreme.

**Comment by StrandedKitty** [comment]
Normal texture for roof tiles had a slight slope baked into it. It should be better now. But besides this normal maps work correctly.
