### ISSUE TITLE
roof:orientation don't work with roof:shape=gambrel

### ISSUE THREAD

**Issue by Kazing** [StrandedKitty/streets-gl#55]
Hello, thanks for this great renderer!

I think there is a bug with handling of `roof:orientation=across`

## `roof:shape=gambrel` with `roof:orientation=across` no working ❌
https://streets.gl/#50.28689,2.78761,43.50,25.75,87.05
https://www.openstreetmap.org/way/144235322

![image](https://user-images.githubusercontent.com/41507326/236416245-9c84f1ec-9b93-43de-aa49-6560406cfccb.png)

The roof ridge is along the longer side, it should be across the longer side with `roof:orientation=across` tag

## `roof:shape=gabled` with `roof:orientation=across` work well ✅
https://streets.gl/#50.28747,2.78603,41.00,351.50,123.96
https://www.openstreetmap.org/way/1110541653

![image](https://user-images.githubusercontent.com/41507326/236416060-89badd32-43b7-4d3e-b2e9-1c86adbd7e7c.png)

**Comment by endim8** [comment]
off topic, but how did you select the building? i didn't know you could do that

**Comment by ivanbranco** [comment]
> off topic, but how did you select the building? i didn't know you could do that

Just a left click, doesn't it work for you?

**Comment by StrandedKitty** [comment]
Implemented in https://github.com/StrandedKitty/streets-gl/commit/cf53d5fae1c4ea9981c44edc4e85f1426b932a74.

<img width="631" alt="Screenshot 2023-05-07 at 14 15 52" src="https://user-images.githubusercontent.com/48140945/236676904-1453e152-c121-4f20-8ca8-a249444aaaac.png">
