### ISSUE TITLE
Building not rendered

### ISSUE THREAD

**Issue by habi** [StrandedKitty/streets-gl#57]
The [Institute of Anatomy in Bern, Switzerland](https://www.ana.unibe.ch) and it's adjacent building is not rendered [on streets.gl](https://streets.gl/#46.95151,7.42945,45.00,0.00,408.23).
I think it is because I've tagged it with several `building:part`s which might be something that your (*awesome*) renderer doesn't take into account as other services do, for example [demo.f4map].(https://demo.f4map.com/#lat=46.9515477&lon=7.4291842&zoom=18)

**Comment by ivanbranco** [comment]
> I think it is because I've tagged it with several `building:part`s which might be something that your (_awesome_) renderer doesn't take into account

Nope, quite the opposite. Streets GL takes **only** building:part's into account, while F4 uses both the outline and the building:parts. As a matter of fact the link you provided shows only the building parts that have been mapped. This because Streets GL follows the Simple 3D Buildings schema, that says:

> When a building has any [building:part](https://wiki.openstreetmap.org/wiki/Key:building:part)=* areas, the building outline is not considered for 3D rendering.

**Comment by westnordost** [comment]
I think it is a tenet rather than a deficiency of streets-gl to stick closely to the specification. This way, streets-gl can be used like a validation tool.

**Comment by ivanbranco** [comment]
> I think it is a tenet rather than a deficiency of streets-gl to stick closely to the specification. This way, streets-gl can be used like a validation tool.

Yep, the problem is that people, to circumvent this rule, tags the outlines as building:part=yes or even building:part=no (which counterintuitively **makes it** a building:part). Another (opposite) example is people tagging outlines with height=0 to "delete" the outline in Jawg 3d map tiles

**Comment by StrandedKitty** [comment]
To circumvent this rule you can use `building=yes` and `building:part=yes` on the outline. I think this not what's in the spec, but it makes sense to prioritize the `building:part=yes` tag in such case, and this is exactly what this renderer does.

Personally, I think it makes sense to allow using these two tags on a single way. By doing this you specify that a way poses as the outline for the whole building (by adding `building=yes`), but also the same way should be rendered as a building part (by adding `building:part=yes`). There's quite a lot of buildings that a mapped this way.

And from the UX point of view when making a 3D building it is much easier for a mapper to just slap one more tag on the existing way compared to adding another way for `building:part`.

**Comment by habi** [comment]
> When a building has any building:part=* areas, the building outline is not considered for 3D rendering.

I always mapped it according to https://wiki.openstreetmap.org/wiki/Key:building:part, where it says that “`building:part=*`are optional areas used in addition to a building=* area. building:part=* areas should always be within a separate building=* area representing the entire building.”
I.e. a building area as outline and then ‘details’ inside with `building:part`.

**Comment by habi** [comment]
Sorry, I have't seen there's already a pinned issue for this: https://github.com/StrandedKitty/streets-gl/issues/3
