### ISSUE TITLE
Feature request: support area:highway=*

### ISSUE THREAD

**Issue by ivanbranco** [StrandedKitty/streets-gl#6]
Hi,

do you think it would be possible to support the area:highway=* tag? It would be cool to see rendered the real width of highways/sidewalks.

![image](https://user-images.githubusercontent.com/94002623/235866708-4905d182-6920-4b1c-a70c-8c018026cc97.png)

**Comment by Matthias84** [comment]
Maybe in combination with footway=crossing etc?

**Comment by Discostu36** [comment]
support for area:highway=footway has been added in c2581103ef8fb270172b0c0de97ab953c1a491e6

![grafik](https://github.com/StrandedKitty/streets-gl/assets/30999326/90a3d8c9-0c06-411f-9702-3ec29f658ce4)

**Comment by StrandedKitty** [comment]
Implemented in https://github.com/StrandedKitty/streets-gl/pull/122.
