### ISSUE TITLE
Add website link to the repository settings

### ISSUE THREAD

**Issue by waldyrious** [StrandedKitty/streets-gl#65]
Currently, when visiting the repository home, one needs to scroll down past the file list and into the README a bit to find a link to the site. It would be nice if the link was also added to the repository settings, so it would appear right after the repository description in a more accessible place.

**Comment by StrandedKitty** [comment]
Thank you, I didn't know there was a field for that.

**Comment by waldyrious** [comment]
Awesome, thanks for the quick fix!
