### ISSUE TITLE
Add option to disable terrain?

### ISSUE THREAD

**Issue by Kovoschiz** [StrandedKitty/streets-gl#7]
I'm trying to debug some buildings. The DEM is not high resolution enough locally with steep ground differences, where there are also many large area carparks at base, podiums and skyscrapers contributing to the inaccuracy. So I want to see whole buildings on a flat surface.  
Unlike F4Maps, there doesn't seem to be a toggle for elevations. Is this a deliberate choice? (I don't know how this rendering works) Or add a new "layer"/scene if not doable in the same view.

**Comment by StrandedKitty** [comment]
Thank yor for the suggestion. Implemented in https://github.com/StrandedKitty/streets-gl/commit/24767c6f0c9b4a0cd67faf37f954c33b49332aa0.
<img width="379" alt="Screenshot 2023-05-05 at 16 17 06" src="https://user-images.githubusercontent.com/48140945/236483641-e277ae14-1d01-4132-a885-b1fd8845e84a.png">
