### ISSUE TITLE
some highway=*_link do not get redered

### ISSUE THREAD

**Issue by osm-ToniE** [StrandedKitty/streets-gl#8]
https://streets.gl/#48.10297,11.65057,65.25,23.25,387.36

https://www.openstreetmap.org/?mlat=48.10324&mlon=11.64992#map=19/48.10324/11.64992

**Comment by osm-ToniE** [comment]
I found some values which do not get rendered

- trunk_link
- primary_link
- secondary_link
- tertiary_link

motorway_link seems to be rendered

**Comment by StrandedKitty** [comment]
Thank you, I've added these highway types in https://github.com/StrandedKitty/streets-gl/commit/0c9f8e3a48f1629a2d2681bae6a8f49c8fba5b26.
