### ISSUE TITLE
building:min_level and building:max_level

### ISSUE THREAD

**Issue by benoit-dd** [StrandedKitty/streets-gl#83]
[min_height](https://wiki.openstreetmap.org/wiki/Key:min%20height) works fine (for ex Tower Bridge: https://www.openstreetmap.org/way/367652753) for building suspended or cantilevered

Are the keys `building:min_level` and `building:max_level` also used?
It doesn't looks ok [here ](https://streets.gl/#48.71122,2.17317,20.00,162.00,388.22)for example:
![image](https://github.com/StrandedKitty/streets-gl/assets/52233014/84414f23-7ebe-4789-9418-df34932eb7f9)

![img_4428 jpg__1170x731_q85_crop_subsampling-2_upscale 1](https://github.com/StrandedKitty/streets-gl/assets/52233014/2a6eaece-40bb-4bea-bdbc-d0e9bb5b208c)

**Comment by ivanbranco** [comment]
> Are the keys building:min_level and building:max_level also used?

Please notice that the correct tags for 3d mapping are building:min_level=* and building:levels=*, and that the tags used on that building are max_level and min_level

Judging on the wiki building:max_level, max_level and min_level are used for indoor tagging, not 3d tagging.

**Comment by benoit-dd** [comment]
oh, yes, sorry. with the correct key+values, it works fine.
