### ISSUE TITLE
Feature Request: show barrier=retaining_wall

### ISSUE THREAD

**Issue by osm-ToniE** [StrandedKitty/streets-gl#85]
https://streets.gl/#48.10982,11.52242,68.25,357.00,479.49

https://www.openstreetmap.org/?mlat=48.11009&mlon=11.52375#map=18/48.11009/11.52375

**Comment by ivanbranco** [comment]
Duplicate of #32 ?

**Comment by osm-ToniE** [comment]
Duplicate to #32
