### ISSUE TITLE
building=no renders as a building

### ISSUE THREAD

**Issue by JacksonMcGough** [StrandedKitty/streets-gl#90]
**Description**
[building=no](https://taginfo.openstreetmap.org/tags/building=no) is a somewhat rare tag used to clarify that a way is not a building when the way otherwise is tagged with keys which would suggest it is a building. Frankly, I'm not sure this is even a standard tag, but as long as folks are using it and the meaning is clear, then streets-gl seemingly shouldn't render these ways as buildings.

**Expected behavior**
Ways tagged with building=no should not render as buildings

**Map location**
You can see three land use ways rendered as buildings [here](https://streets.gl/#44.91565,-92.93987,42.00,343.75,1216.46).

**Screenshots**
![image](https://github.com/StrandedKitty/streets-gl/assets/16675448/11a58281-5767-4852-b384-f0ca2362040d)

_P.S.: This is my first time submitting a bug report on GitHub, so apologies if I committed any faux pas._

**Comment by StrandedKitty** [comment]
Thank you. Your bug report is perfect!

Fixed in https://github.com/StrandedKitty/streets-gl/commit/cd57913dbed5f163c1ea18a4091f7c075b6a6a4f.
