### ISSUE TITLE
The Void has opened up in Stratford

### ISSUE THREAD

**Issue by hb0nd** [StrandedKitty/streets-gl#99]
it's fine when disabling terrain data, might be an issue with esri.

**Map location**
https://streets.gl/#51.53532,-0.01789,25.25,347.50,3990.51

**Screenshots**

![image](https://github.com/StrandedKitty/streets-gl/assets/26939824/62fcb149-2145-45d0-ae9b-1b6a33165d47)

**System information**
 - OS: Fedora 38
 - Browser with version: Firefox 113

**Comment by StrandedKitty** [comment]
Fixed.
<img width="1071" alt="Screenshot 2023-05-21 at 21 16 51" src="https://github.com/StrandedKitty/streets-gl/assets/48140945/f3673084-9fcd-4a3a-aa6a-5d289c20c724">
